"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.alertbox = exports.warningbox = exports.successbox = exports.detectErrorResponse = exports.parseErrorThrown = exports.submitFailure = exports.stopWaiting = exports.startWaiting = exports.openNewWindow = exports.submitWindow = exports.addWindow = exports.closeChildWindows = exports.getWindowByName = exports.loadAppConfig = exports.assignAppConfig = exports.getMultiLanguagesModel = exports.appInit = exports.setBaseCss = exports.getBaseCss = exports.setProgramLabels = exports.setDefaultLabels = exports.setProgramMessage = exports.getProgramLabels = exports.getDefaultLabels = exports.getProgramMessage = exports.isSecureStorage = exports.setSecureStorage = exports.setDefaultRawParameters = exports.setBaseStorage = exports.setChatUrl = exports.setImgUrl = exports.setCdnUrl = exports.setBaseUrl = exports.setApiUrl = exports.setApiToken = exports.getDefaultRawParameters = exports.getBaseStorage = exports.getChatUrl = exports.getImgUrl = exports.getCdnUrl = exports.getBaseUrl = exports.getApiUrl = exports.getApiToken = exports.setDefaultLanguage = exports.getDefaultLanguage = exports.setMultiLanguages = exports.getMultiLanguages = exports.registerNotification = exports.getAppInfo = exports.DEFAULT_CONTENT_TYPE = void 0;
exports.formatDataTable = exports.ensureTableSetting = exports.formatDecimal = exports.formatFloating = exports.removeDelimiter = exports.removeComma = exports.parseNumber = exports.setCaretPosition = exports.getCaretPosition = exports.clearComma = exports.putComma = exports.formatNumber = exports.checkInputKey = exports.checkInputNumberOnly = exports.inputNumberOnly = exports.triggerInput = exports.openCalendar = exports.clearCalendar = exports.getControlClasses = exports.disableControls = exports.createLinkStyle = exports.decryptCipherData = exports.serializeParameters = exports.setupApplication = exports.startApplication = exports.confirmRevise = exports.confirmResend = exports.confirmExport = exports.confirmImport = exports.confirmRequest = exports.confirmReject = exports.confirmApprove = exports.confirmErase = exports.confirmReset = exports.confirmReceive = exports.confirmSaveAs = exports.confirmProcess = exports.confirmClear = exports.confirmUpdate = exports.confirmSend = exports.confirmRemove = exports.confirmCancel = exports.confirmSave = exports.confirmDelete = exports.confirmDialogBox = exports.confirmmsg = exports.alertmsg = exports.confirmDialog = exports.confirmbox = exports.alertDialog = void 0;
exports.Utilities = exports.randomNumber = exports.random = exports.getRandomNumber = exports.NUMERICS = exports.ALPHABETS = exports.checkNumberOnly = exports.createNewPassword = exports.indexOfAlphabets = exports.isUpperCase = exports.isLowerCase = exports.isLetter = exports.isDigit = exports.getDigits = exports.getAlphabets = exports.randomPassword = exports.loadPermissions = exports.getPermitModel = exports.Permission = exports.DEFAULT_PERMITS = exports.DEFAULT_PAGE_SETTINGS = exports.Paging = exports.replaceString = exports.getMessageCode = exports.bindingParentMessaging = exports.bindingChildMessaging = exports.getDH = exports.setupDiffie = exports.handleRequestMessage = exports.sendMessageToOpener = exports.sendMessageToParent = exports.requestAccessorInfo = exports.sendMessageToFrame = exports.sendMessageInterface = exports.removeAccessorInfo = exports.saveAccessorInfo = exports.getAccessorToken = exports.getAccessorInfo = exports.removeStorage = exports.setStorage = exports.getStorage = exports.getCurrentWindow = exports.setCurrentWindow = exports.setMessagingCallback = exports.getLabelModel = exports.getLabelObject = exports.getLabelItem = exports.getLabel = exports.KnMask = exports.DH = void 0;
exports.bootbox = void 0;
const bootbox_1 = __importDefault(require("./bootbox/bootbox"));
exports.bootbox = bootbox_1.default;
var app_info_1 = require("./app/app.info");
Object.defineProperty(exports, "DEFAULT_CONTENT_TYPE", { enumerable: true, get: function () { return app_info_1.DEFAULT_CONTENT_TYPE; } });
Object.defineProperty(exports, "getAppInfo", { enumerable: true, get: function () { return app_info_1.getAppInfo; } });
Object.defineProperty(exports, "registerNotification", { enumerable: true, get: function () { return app_info_1.registerNotification; } });
Object.defineProperty(exports, "getMultiLanguages", { enumerable: true, get: function () { return app_info_1.getMultiLanguages; } });
Object.defineProperty(exports, "setMultiLanguages", { enumerable: true, get: function () { return app_info_1.setMultiLanguages; } });
Object.defineProperty(exports, "getDefaultLanguage", { enumerable: true, get: function () { return app_info_1.getDefaultLanguage; } });
Object.defineProperty(exports, "setDefaultLanguage", { enumerable: true, get: function () { return app_info_1.setDefaultLanguage; } });
Object.defineProperty(exports, "getApiToken", { enumerable: true, get: function () { return app_info_1.getApiToken; } });
Object.defineProperty(exports, "getApiUrl", { enumerable: true, get: function () { return app_info_1.getApiUrl; } });
Object.defineProperty(exports, "getBaseUrl", { enumerable: true, get: function () { return app_info_1.getBaseUrl; } });
Object.defineProperty(exports, "getCdnUrl", { enumerable: true, get: function () { return app_info_1.getCdnUrl; } });
Object.defineProperty(exports, "getImgUrl", { enumerable: true, get: function () { return app_info_1.getImgUrl; } });
Object.defineProperty(exports, "getChatUrl", { enumerable: true, get: function () { return app_info_1.getChatUrl; } });
Object.defineProperty(exports, "getBaseStorage", { enumerable: true, get: function () { return app_info_1.getBaseStorage; } });
Object.defineProperty(exports, "getDefaultRawParameters", { enumerable: true, get: function () { return app_info_1.getDefaultRawParameters; } });
Object.defineProperty(exports, "setApiToken", { enumerable: true, get: function () { return app_info_1.setApiToken; } });
Object.defineProperty(exports, "setApiUrl", { enumerable: true, get: function () { return app_info_1.setApiUrl; } });
Object.defineProperty(exports, "setBaseUrl", { enumerable: true, get: function () { return app_info_1.setBaseUrl; } });
Object.defineProperty(exports, "setCdnUrl", { enumerable: true, get: function () { return app_info_1.setCdnUrl; } });
Object.defineProperty(exports, "setImgUrl", { enumerable: true, get: function () { return app_info_1.setImgUrl; } });
Object.defineProperty(exports, "setChatUrl", { enumerable: true, get: function () { return app_info_1.setChatUrl; } });
Object.defineProperty(exports, "setBaseStorage", { enumerable: true, get: function () { return app_info_1.setBaseStorage; } });
Object.defineProperty(exports, "setDefaultRawParameters", { enumerable: true, get: function () { return app_info_1.setDefaultRawParameters; } });
Object.defineProperty(exports, "setSecureStorage", { enumerable: true, get: function () { return app_info_1.setSecureStorage; } });
Object.defineProperty(exports, "isSecureStorage", { enumerable: true, get: function () { return app_info_1.isSecureStorage; } });
Object.defineProperty(exports, "getProgramMessage", { enumerable: true, get: function () { return app_info_1.getProgramMessage; } });
Object.defineProperty(exports, "getDefaultLabels", { enumerable: true, get: function () { return app_info_1.getDefaultLabels; } });
Object.defineProperty(exports, "getProgramLabels", { enumerable: true, get: function () { return app_info_1.getProgramLabels; } });
Object.defineProperty(exports, "setProgramMessage", { enumerable: true, get: function () { return app_info_1.setProgramMessage; } });
Object.defineProperty(exports, "setDefaultLabels", { enumerable: true, get: function () { return app_info_1.setDefaultLabels; } });
Object.defineProperty(exports, "setProgramLabels", { enumerable: true, get: function () { return app_info_1.setProgramLabels; } });
Object.defineProperty(exports, "getBaseCss", { enumerable: true, get: function () { return app_info_1.getBaseCss; } });
Object.defineProperty(exports, "setBaseCss", { enumerable: true, get: function () { return app_info_1.setBaseCss; } });
Object.defineProperty(exports, "appInit", { enumerable: true, get: function () { return app_info_1.appInit; } });
Object.defineProperty(exports, "getMultiLanguagesModel", { enumerable: true, get: function () { return app_info_1.getMultiLanguagesModel; } });
Object.defineProperty(exports, "assignAppConfig", { enumerable: true, get: function () { return app_info_1.assignAppConfig; } });
Object.defineProperty(exports, "loadAppConfig", { enumerable: true, get: function () { return app_info_1.loadAppConfig; } });
var app_util_1 = require("./app/app.util");
Object.defineProperty(exports, "getWindowByName", { enumerable: true, get: function () { return app_util_1.getWindowByName; } });
Object.defineProperty(exports, "closeChildWindows", { enumerable: true, get: function () { return app_util_1.closeChildWindows; } });
Object.defineProperty(exports, "addWindow", { enumerable: true, get: function () { return app_util_1.addWindow; } });
Object.defineProperty(exports, "submitWindow", { enumerable: true, get: function () { return app_util_1.submitWindow; } });
Object.defineProperty(exports, "openNewWindow", { enumerable: true, get: function () { return app_util_1.openNewWindow; } });
Object.defineProperty(exports, "startWaiting", { enumerable: true, get: function () { return app_util_1.startWaiting; } });
Object.defineProperty(exports, "stopWaiting", { enumerable: true, get: function () { return app_util_1.stopWaiting; } });
Object.defineProperty(exports, "submitFailure", { enumerable: true, get: function () { return app_util_1.submitFailure; } });
Object.defineProperty(exports, "parseErrorThrown", { enumerable: true, get: function () { return app_util_1.parseErrorThrown; } });
Object.defineProperty(exports, "detectErrorResponse", { enumerable: true, get: function () { return app_util_1.detectErrorResponse; } });
Object.defineProperty(exports, "successbox", { enumerable: true, get: function () { return app_util_1.successbox; } });
Object.defineProperty(exports, "warningbox", { enumerable: true, get: function () { return app_util_1.warningbox; } });
Object.defineProperty(exports, "alertbox", { enumerable: true, get: function () { return app_util_1.alertbox; } });
Object.defineProperty(exports, "alertDialog", { enumerable: true, get: function () { return app_util_1.alertDialog; } });
Object.defineProperty(exports, "confirmbox", { enumerable: true, get: function () { return app_util_1.confirmbox; } });
Object.defineProperty(exports, "confirmDialog", { enumerable: true, get: function () { return app_util_1.confirmDialog; } });
Object.defineProperty(exports, "alertmsg", { enumerable: true, get: function () { return app_util_1.alertmsg; } });
Object.defineProperty(exports, "confirmmsg", { enumerable: true, get: function () { return app_util_1.confirmmsg; } });
Object.defineProperty(exports, "confirmDialogBox", { enumerable: true, get: function () { return app_util_1.confirmDialogBox; } });
Object.defineProperty(exports, "confirmDelete", { enumerable: true, get: function () { return app_util_1.confirmDelete; } });
Object.defineProperty(exports, "confirmSave", { enumerable: true, get: function () { return app_util_1.confirmSave; } });
Object.defineProperty(exports, "confirmCancel", { enumerable: true, get: function () { return app_util_1.confirmCancel; } });
Object.defineProperty(exports, "confirmRemove", { enumerable: true, get: function () { return app_util_1.confirmRemove; } });
Object.defineProperty(exports, "confirmSend", { enumerable: true, get: function () { return app_util_1.confirmSend; } });
Object.defineProperty(exports, "confirmUpdate", { enumerable: true, get: function () { return app_util_1.confirmUpdate; } });
Object.defineProperty(exports, "confirmClear", { enumerable: true, get: function () { return app_util_1.confirmClear; } });
Object.defineProperty(exports, "confirmProcess", { enumerable: true, get: function () { return app_util_1.confirmProcess; } });
Object.defineProperty(exports, "confirmSaveAs", { enumerable: true, get: function () { return app_util_1.confirmSaveAs; } });
Object.defineProperty(exports, "confirmReceive", { enumerable: true, get: function () { return app_util_1.confirmReceive; } });
Object.defineProperty(exports, "confirmReset", { enumerable: true, get: function () { return app_util_1.confirmReset; } });
Object.defineProperty(exports, "confirmErase", { enumerable: true, get: function () { return app_util_1.confirmErase; } });
Object.defineProperty(exports, "confirmApprove", { enumerable: true, get: function () { return app_util_1.confirmApprove; } });
Object.defineProperty(exports, "confirmReject", { enumerable: true, get: function () { return app_util_1.confirmReject; } });
Object.defineProperty(exports, "confirmRequest", { enumerable: true, get: function () { return app_util_1.confirmRequest; } });
Object.defineProperty(exports, "confirmImport", { enumerable: true, get: function () { return app_util_1.confirmImport; } });
Object.defineProperty(exports, "confirmExport", { enumerable: true, get: function () { return app_util_1.confirmExport; } });
Object.defineProperty(exports, "confirmResend", { enumerable: true, get: function () { return app_util_1.confirmResend; } });
Object.defineProperty(exports, "confirmRevise", { enumerable: true, get: function () { return app_util_1.confirmRevise; } });
Object.defineProperty(exports, "startApplication", { enumerable: true, get: function () { return app_util_1.startApplication; } });
Object.defineProperty(exports, "setupApplication", { enumerable: true, get: function () { return app_util_1.setupApplication; } });
Object.defineProperty(exports, "serializeParameters", { enumerable: true, get: function () { return app_util_1.serializeParameters; } });
Object.defineProperty(exports, "decryptCipherData", { enumerable: true, get: function () { return app_util_1.decryptCipherData; } });
Object.defineProperty(exports, "createLinkStyle", { enumerable: true, get: function () { return app_util_1.createLinkStyle; } });
Object.defineProperty(exports, "disableControls", { enumerable: true, get: function () { return app_util_1.disableControls; } });
var ctrl_util_1 = require("./app/ctrl.util");
Object.defineProperty(exports, "getControlClasses", { enumerable: true, get: function () { return ctrl_util_1.getControlClasses; } });
Object.defineProperty(exports, "clearCalendar", { enumerable: true, get: function () { return ctrl_util_1.clearCalendar; } });
Object.defineProperty(exports, "openCalendar", { enumerable: true, get: function () { return ctrl_util_1.openCalendar; } });
Object.defineProperty(exports, "triggerInput", { enumerable: true, get: function () { return ctrl_util_1.triggerInput; } });
Object.defineProperty(exports, "inputNumberOnly", { enumerable: true, get: function () { return ctrl_util_1.inputNumberOnly; } });
Object.defineProperty(exports, "checkInputNumberOnly", { enumerable: true, get: function () { return ctrl_util_1.checkInputNumberOnly; } });
Object.defineProperty(exports, "checkInputKey", { enumerable: true, get: function () { return ctrl_util_1.checkInputKey; } });
Object.defineProperty(exports, "formatNumber", { enumerable: true, get: function () { return ctrl_util_1.formatNumber; } });
Object.defineProperty(exports, "putComma", { enumerable: true, get: function () { return ctrl_util_1.putComma; } });
Object.defineProperty(exports, "clearComma", { enumerable: true, get: function () { return ctrl_util_1.clearComma; } });
Object.defineProperty(exports, "getCaretPosition", { enumerable: true, get: function () { return ctrl_util_1.getCaretPosition; } });
Object.defineProperty(exports, "setCaretPosition", { enumerable: true, get: function () { return ctrl_util_1.setCaretPosition; } });
Object.defineProperty(exports, "parseNumber", { enumerable: true, get: function () { return ctrl_util_1.parseNumber; } });
Object.defineProperty(exports, "removeComma", { enumerable: true, get: function () { return ctrl_util_1.removeComma; } });
Object.defineProperty(exports, "removeDelimiter", { enumerable: true, get: function () { return ctrl_util_1.removeDelimiter; } });
Object.defineProperty(exports, "formatFloating", { enumerable: true, get: function () { return ctrl_util_1.formatFloating; } });
Object.defineProperty(exports, "formatDecimal", { enumerable: true, get: function () { return ctrl_util_1.formatDecimal; } });
Object.defineProperty(exports, "ensureTableSetting", { enumerable: true, get: function () { return ctrl_util_1.ensureTableSetting; } });
Object.defineProperty(exports, "formatDataTable", { enumerable: true, get: function () { return ctrl_util_1.formatDataTable; } });
var dh_1 = require("./app/dh");
Object.defineProperty(exports, "DH", { enumerable: true, get: function () { return dh_1.DH; } });
var KnMask_1 = require("./app/KnMask");
Object.defineProperty(exports, "KnMask", { enumerable: true, get: function () { return KnMask_1.KnMask; } });
var label_util_1 = require("./app/label.util");
Object.defineProperty(exports, "getLabel", { enumerable: true, get: function () { return label_util_1.getLabel; } });
Object.defineProperty(exports, "getLabelItem", { enumerable: true, get: function () { return label_util_1.getLabelItem; } });
Object.defineProperty(exports, "getLabelObject", { enumerable: true, get: function () { return label_util_1.getLabelObject; } });
Object.defineProperty(exports, "getLabelModel", { enumerable: true, get: function () { return label_util_1.getLabelModel; } });
var messenger_1 = require("./app/messenger");
Object.defineProperty(exports, "setMessagingCallback", { enumerable: true, get: function () { return messenger_1.setMessagingCallback; } });
Object.defineProperty(exports, "setCurrentWindow", { enumerable: true, get: function () { return messenger_1.setCurrentWindow; } });
Object.defineProperty(exports, "getCurrentWindow", { enumerable: true, get: function () { return messenger_1.getCurrentWindow; } });
Object.defineProperty(exports, "getStorage", { enumerable: true, get: function () { return messenger_1.getStorage; } });
Object.defineProperty(exports, "setStorage", { enumerable: true, get: function () { return messenger_1.setStorage; } });
Object.defineProperty(exports, "removeStorage", { enumerable: true, get: function () { return messenger_1.removeStorage; } });
Object.defineProperty(exports, "getAccessorInfo", { enumerable: true, get: function () { return messenger_1.getAccessorInfo; } });
Object.defineProperty(exports, "getAccessorToken", { enumerable: true, get: function () { return messenger_1.getAccessorToken; } });
Object.defineProperty(exports, "saveAccessorInfo", { enumerable: true, get: function () { return messenger_1.saveAccessorInfo; } });
Object.defineProperty(exports, "removeAccessorInfo", { enumerable: true, get: function () { return messenger_1.removeAccessorInfo; } });
Object.defineProperty(exports, "sendMessageInterface", { enumerable: true, get: function () { return messenger_1.sendMessageInterface; } });
Object.defineProperty(exports, "sendMessageToFrame", { enumerable: true, get: function () { return messenger_1.sendMessageToFrame; } });
Object.defineProperty(exports, "requestAccessorInfo", { enumerable: true, get: function () { return messenger_1.requestAccessorInfo; } });
Object.defineProperty(exports, "sendMessageToParent", { enumerable: true, get: function () { return messenger_1.sendMessageToParent; } });
Object.defineProperty(exports, "sendMessageToOpener", { enumerable: true, get: function () { return messenger_1.sendMessageToOpener; } });
Object.defineProperty(exports, "handleRequestMessage", { enumerable: true, get: function () { return messenger_1.handleRequestMessage; } });
Object.defineProperty(exports, "setupDiffie", { enumerable: true, get: function () { return messenger_1.setupDiffie; } });
Object.defineProperty(exports, "getDH", { enumerable: true, get: function () { return messenger_1.getDH; } });
Object.defineProperty(exports, "bindingChildMessaging", { enumerable: true, get: function () { return messenger_1.bindingChildMessaging; } });
Object.defineProperty(exports, "bindingParentMessaging", { enumerable: true, get: function () { return messenger_1.bindingParentMessaging; } });
var msg_util_1 = require("./app/msg.util");
Object.defineProperty(exports, "getMessageCode", { enumerable: true, get: function () { return msg_util_1.getMessageCode; } });
Object.defineProperty(exports, "replaceString", { enumerable: true, get: function () { return msg_util_1.replaceString; } });
var Paging_1 = require("./app/Paging");
Object.defineProperty(exports, "Paging", { enumerable: true, get: function () { return Paging_1.Paging; } });
Object.defineProperty(exports, "DEFAULT_PAGE_SETTINGS", { enumerable: true, get: function () { return Paging_1.DEFAULT_PAGE_SETTINGS; } });
var permit_util_1 = require("./app/permit.util");
Object.defineProperty(exports, "DEFAULT_PERMITS", { enumerable: true, get: function () { return permit_util_1.DEFAULT_PERMITS; } });
Object.defineProperty(exports, "Permission", { enumerable: true, get: function () { return permit_util_1.Permission; } });
Object.defineProperty(exports, "getPermitModel", { enumerable: true, get: function () { return permit_util_1.getPermitModel; } });
Object.defineProperty(exports, "loadPermissions", { enumerable: true, get: function () { return permit_util_1.loadPermissions; } });
var pwd_util_1 = require("./app/pwd.util");
Object.defineProperty(exports, "randomPassword", { enumerable: true, get: function () { return pwd_util_1.randomPassword; } });
Object.defineProperty(exports, "getAlphabets", { enumerable: true, get: function () { return pwd_util_1.getAlphabets; } });
Object.defineProperty(exports, "getDigits", { enumerable: true, get: function () { return pwd_util_1.getDigits; } });
Object.defineProperty(exports, "isDigit", { enumerable: true, get: function () { return pwd_util_1.isDigit; } });
Object.defineProperty(exports, "isLetter", { enumerable: true, get: function () { return pwd_util_1.isLetter; } });
Object.defineProperty(exports, "isLowerCase", { enumerable: true, get: function () { return pwd_util_1.isLowerCase; } });
Object.defineProperty(exports, "isUpperCase", { enumerable: true, get: function () { return pwd_util_1.isUpperCase; } });
Object.defineProperty(exports, "indexOfAlphabets", { enumerable: true, get: function () { return pwd_util_1.indexOfAlphabets; } });
Object.defineProperty(exports, "createNewPassword", { enumerable: true, get: function () { return pwd_util_1.createNewPassword; } });
Object.defineProperty(exports, "checkNumberOnly", { enumerable: true, get: function () { return pwd_util_1.checkNumberOnly; } });
var random_util_1 = require("./app/random.util");
Object.defineProperty(exports, "ALPHABETS", { enumerable: true, get: function () { return random_util_1.ALPHABETS; } });
Object.defineProperty(exports, "NUMERICS", { enumerable: true, get: function () { return random_util_1.NUMERICS; } });
Object.defineProperty(exports, "getRandomNumber", { enumerable: true, get: function () { return random_util_1.getRandomNumber; } });
Object.defineProperty(exports, "random", { enumerable: true, get: function () { return random_util_1.random; } });
Object.defineProperty(exports, "randomNumber", { enumerable: true, get: function () { return random_util_1.randomNumber; } });
var Utilities_1 = require("./app/Utilities");
Object.defineProperty(exports, "Utilities", { enumerable: true, get: function () { return Utilities_1.Utilities; } });
